### ISSUE TITLE
Feature: adding custom background colour input for easier contrast check

### ISSUE THREAD

**Issue by luuu-xu** [samrobbins85/colour-a11y-for-tailwind#32]
I love the idea of this web app! Great job creating this and making it super pretty too!

Can we add a custom background colour input for both light mode and dark mode, instead of the default white and black? I believe adding this input would help a lot of developers to choose appropriate colour for meeting AA or AAA rating (because I have been using coolors etc and simply copying and pasting from Tailwind docs...)

I would also love to work on this feature myself!

**Comment by samrobbins85** [comment]
Yeah that'd be great thanks!

**Comment by luuu-xu** [comment]
@samrobbins85 I just created the PR and please take a look. I also think it is another good feature if we can change the scores' text colours to, let's say, for AAA you get `#22C55E` green, and for AA you get `#FACC15`, and for Fail you get `#EF4444`. What do you think?

**Comment by luuu-xu** [comment]
@samrobbins85 Hi just let me know what you think about the PR and my proposed new feature too! I would love to make this tool better and more useful and share it with everyone focused on a11y and colour contrast with Tailwind!

**Comment by samrobbins85** [comment]
Hi, sorry I've been quite busy recently, I'll try to take a look at it this week

**Comment by samrobbins85** [comment]
Looks great, merged
