### ISSUE TITLE
Use Tailwind classes for background colors

### ISSUE THREAD

**Issue by thischrisblack** [samrobbins85/colour-a11y-for-tailwind#37]
For my use case, I'd be checking the foreground text color against specific Tailwind background colors, so it would be extra-helpful to use Tailwind class names in the background color selectors rather than the html color inputs that are currently there. Maybe it would be a little panel with two dropdowns, one dropdown for the color name, and the other for the "100, 200, 300, etc." value?

**Comment by samrobbins85** [comment]
Thanks for the suggestion! I've now added this

**Comment by thischrisblack** [comment]
Thanks!
